language: node_js
node_js:
  - "11.0"
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token: 1//0h6L3MkqVQbqqCgYIARAAGBESNwF-L9Irt6-vGgN7VgscCO8f7ByZDK8ZRgPQ6bSGOE6jjntxfSZzH4V08Wus1CPMMkWl-x5C5_o
    secure: ""
